### PR TITLE
Clear flash before showing next flash.

### PR DESCRIPTION
**Pull request by spellman**
Hi! I'm not sure of the proper procedure for submitting pull requests so I'm sorry if I should have contacted you beforehand :) Anyway, I ran into the following issue and made the change in this commit to solve it. (I'm using the bootstrap version but I made parallel changes to the non-bootstrap version as well.)

The flash was not being cleared when ajax links were clicked:
-   If the link resulted in no flash, then the existing flash persisted.
-   If the link resulted in a flash, then it was prepended into the flash container, resulting in two flashes.

Since the idea of the flash is to display a message in response to one user action and then disappear,
-   If there is no flash to display, then I clear any existing flash.
-   If there is a flash to display, then I clear any existing flash and display the new flash.

Let me know if you'd like me to make any changes to this patch.

Note: Is this related to the following?
-   https://github.com/leonid-shevtsov/unobtrusive_flash/issues/23
-   https://github.com/leonid-shevtsov/unobtrusive_flash/issues/18

### CODE REVIEW

**Comment by leonid-shevtsov** [comment]
Hi, the proper procedure is just submitting a PR, so you're doing everything right. I'll review the changes some time soon; if they fix the mentioned issues that'd be great.

**Comment by spellman** [comment]
Cool.

I was thinking that since some showFlash() is called after every
ajaxComplete, clearing the flash may not be desirable. An unrelated update
on the page could cause the flash to be cleared while it's still useful to
the user.
In that case, stacking flashes might be a better choice.
Or, maybe the flash isn't the tool for that job and clearing is ok. It made
sense for my use case, where I have a form and a display panel on the same
page and I ajaxified certain links to avoid superfluous refreshes of the
display.

**Comment by ekampp** [comment]
There might be a situation, where multiple flashes is needed. So I think clearing the flash before display should be optional (either opt-in or -out).

**Comment by spellman** [comment]
Opt-in sounds good. Let me see what I can do...

**Comment by spellman** [comment]
Sorry for the long delay!

1) Is this whole thing a bad idea? Of course, that's fine if so - just close this :)

2) If not, I'm thinking the opt-in would be a setting, either on the ruby side (sets it for all clients) or on the js side (per-client flexibility). Any thoughts as to where it should go?

**Comment by ekampp** [comment]
I think it's a fine feature - as long as it's opt-in.

**Comment by spellman** [comment]
I amended the previous commit, adding the setting UnobtrusiveFlash.flashOptions.clearFlashOnNextRequest, with a default of false. I added integration tests as well.

What do y'all think?

**Comment by spellman** [comment]
I changed it to remove children of the flash container:
- div.alert children for Bootstrap
- div.unobtrusive-flash-message-wrapper children for non-Bootstrap

That may still remove all .alert divs from body in the Bootstrap case. Is that acceptable or would be it better to add an extra class to the Bootstrap messages and remove elements with that class?

**Comment by ekampp** [comment]
Are people using the `.alert` class on other elements? It's a pretty general class, right? If we're removing all `div.alert` in the body, then we might be removing other content that's styled with an alert class. 

For me this isn't a problem, I'm just thinking out loud :)

**Comment by spellman** [comment]
1.  Yeah. I've added the `.unobtrusive-flash-message` class to Bootstrap message `div` elements in order to remove only those elements.

2.  I'm not seeing this failure locally: https://travis-ci.org/leonid-shevtsov/unobtrusive_flash/jobs/115890746
(Locally, I set Ruby 2.0.0-p598 via rbenv, jQuery 1.11.1 via spec_helper environment variable, and Rails 4.0 ran as part of `appraisal rake spec`.)
**Any ideas as to what's causing the failure or how to reproduce it?**

**Comment by pabse** [comment]
Thats exactly the feature I'm currently looking for. 👍 
Any progress?

**Comment by spellman** [comment]
I couldn't get one of the tests to pass in one ruby environment on the CI
server and I couldn't reproduce the failure locally.
I'll try again this weekend.

**Pull request closed without merging**
